# Generated by Django 5.2.3 on 2025-06-16 01:47

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="config",
            managers=[
                ("config", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="detection",
            managers=[
                ("detections", django.db.models.manager.Manager()),
            ],
        ),
    ]
