# Generated by Django 5.2.3 on 2025-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_config_managers_alter_detection_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="timezone",
            field=models.CharField(default="US/Pacific"),
        ),
    ]
