# Generated by Django 5.2.3 on 2025-06-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_config_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="timezone",
        ),
    ]
